#!/usr/bin/env bash
# Work Stop hook — auto-save handoff, release lock, set status to paused.
# Only acts if forge is actively running.
#
# Input:  JSON on stdin from Claude Code Stop event
# Output: JSON on stdout (or nothing for no-op)
#
# CRITICAL: Uses jq for all JSON construction.
#
# Every exit path must write to stderr to prevent Claude Code's "No stderr
# output" feedback from creating an infinite conversation loop.

set -uo pipefail
trap '[ $? -eq 0 ] && echo "forge: ok" >&2 || echo "forge: error" >&2' EXIT

# F050: the circuit-breaker check used to run here, before ANY of the
# checkpoint work below (handoff write, status=paused, lock release). A
# tripped breaker calls `exit 0` immediately, so every one of those steps
# was silently skipped on a trip -- leaking .forge/lock.json (status stuck
# at "running") and forcing the next resume to wait out the 30-minute
# stale-heartbeat window instead of getting a paused state + handoff to act
# on. The breaker exists to suppress a runaway RE-INVOCATION, not to
# suppress crash-safe cleanup, so it is now checked further down (see
# "Circuit breaker" below) -- AFTER the durable checkpoint, immediately
# before the one thing it should actually gate: queuing the freshen
# auto-resume signal.

# Locate project directory
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-}"

if [[ -z "$PROJECT_DIR" ]]; then
  INPUT="$(cat)" || exit 0
  PROJECT_DIR="$(printf '%s' "$INPUT" | jq -r '.cwd // empty' 2>/dev/null)" || exit 0
else
  cat > /dev/null 2>&1 || true
fi

[[ -z "$PROJECT_DIR" ]] && exit 0

# Check for forge state
STATE_FILE="${PROJECT_DIR}/.forge/state.json"
[[ ! -f "$STATE_FILE" ]] && exit 0

# Verify jq is available. This is NOT the "plugin inactive" silent-skip
# case (state.json existing means forge IS active) -- a missing jq here is
# a real environment defect worth surfacing (F054).
if ! command -v jq &>/dev/null; then
  echo "forge: session-stop: jq not found -- cannot checkpoint forge state" >&2
  exit 0
fi

# Read status — only act if running. F054: a malformed state.json used to
# fail this jq call and exit 0 completely silently; log it instead.
STATUS="$(jq -r '.status // empty' "$STATE_FILE")"
JQ_STATUS=$?
if [[ $JQ_STATUS -ne 0 ]]; then
  echo "forge: session-stop: ${STATE_FILE} is unreadable/malformed (jq exit ${JQ_STATUS}) -- skipping checkpoint" >&2
  exit 0
fi
if [[ "$STATUS" != "running" ]]; then
  exit 0
fi

# --- Portability helpers ---

# F055: parse an ISO-8601 UTC timestamp into epoch seconds without GNU-only
# `date -d` (illegal option on BSD/macOS -- Mikey's primary machine). jq's
# own `fromdate` parses ISO-8601 identically on every platform jq runs on,
# matching the pattern forge-lock.sh already established (see its
# `lock_age_seconds`/`now_iso` — "All date arithmetic uses jq's
# now/todate/fromdate builtins rather than date -d"). `try/catch empty`
# guards against a non-ISO-8601 string reaching an unguarded `fromdate`.
duration_since() {
  local iso="$1"
  jq -n -r --arg t "$iso" 'try ((now - ($t | fromdate)) | floor) catch empty' 2>/dev/null
}

# F051: bound a command by a hard wall-clock timeout so it can never eat
# the whole 15s hook budget and truncate the checkpoint. Stock macOS ships
# neither GNU `timeout` nor a BSD equivalent -- prefer `timeout`, fall back
# to Homebrew coreutils' `gtimeout`, and if neither exists, signal that to
# the caller (exit 127) rather than risk an unbounded hang.
run_with_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then
    timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then
    gtimeout "$secs" "$@"
  else
    return 127
  fi
}

# Derive session duration from lock
LOCK_FILE="${PROJECT_DIR}/.forge/lock.json"
DURATION="unknown"
if [[ -f "$LOCK_FILE" ]]; then
  ACQUIRED_AT="$(jq -r '.acquired_at // empty' "$LOCK_FILE" 2>/dev/null)"
  if [[ -n "$ACQUIRED_AT" ]]; then
    DURATION_SECS="$(duration_since "$ACQUIRED_AT")"
    if [[ "$DURATION_SECS" =~ ^-?[0-9]+$ ]]; then
      DURATION="${DURATION_SECS}s"
    fi
  fi
fi

# Write handoff with degraded marker to handoffs directory
mkdir -p "${PROJECT_DIR}/.forge/handoffs"
HANDOFF_FILE="${PROJECT_DIR}/.forge/handoffs/handoff-execute.md"
STORIES_ATTEMPTED="$(jq -r '.stories_attempted // 0' "$STATE_FILE" 2>/dev/null)"
STORIES_THIS="$(jq -r '.stories_this_session // 0' "$STATE_FILE" 2>/dev/null)"

cat > "$HANDOFF_FILE" <<EOF
# Work Handoff

## WARNING: Incomplete Handoff
This handoff was auto-generated by the stop hook. It lacks working context
(patterns, micro-decisions, code landmarks) that a graceful /forge stop would include.
- **source**: stop-hook
- **timestamp**: $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Session Summary
- **Duration**: ${DURATION}
- **Stories completed this session**: ${STORIES_THIS}
- **Stories attempted total**: ${STORIES_ATTEMPTED}
- **Status**: Session ended (stop hook)

## What Happened
Session was terminated (Claude Code stop event). Handoff auto-saved by stop hook.

## What's Next
Run \`/forge resume\` to continue.
EOF

# F050/F051: the durable checkpoint (status=paused + increment counters +
# lock release) runs next, UNCONDITIONALLY -- before the optional storyhook
# narrative and before the circuit-breaker check. Neither a hung `story`
# process nor a tripped breaker may block or skip this: it is the one thing
# a crash-safe Stop hook must always get through.

# Update state in a single jq pipeline: set paused + increment sessions_completed + pre-compute resume context
jq --arg hf "handoffs/handoff-execute.md" \
   --arg sum "Session interrupted (stop hook). ${STORIES_THIS} stories this session, ${STORIES_ATTEMPTED} total. Duration: ${DURATION}. Degraded handoff." \
   --arg cmd "/forge resume" \
   '.status = "paused"
    | .sessions_completed = (.sessions_completed + 1)
    | .updated_at = (now | todate)
    | .resume = {command: $cmd, handoff_file: $hf, summary: $sum}' \
  "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"

# Release lock
rm -f "$LOCK_FILE"

# Generate storyhook handoff if story CLI is available. F051: this used to
# run BEFORE the durable checkpoint above with no timeout, so a hung/slow
# `story` process could burn the entire 15s hook budget and get killed
# before status=paused/lock-release ever ran. It now runs AFTER the
# checkpoint (a hang here can no longer block it) and bounded by a hard
# timeout well under the hook's 15s budget.
if command -v story &>/dev/null; then
  STORY_HANDOFF="$(cd "$PROJECT_DIR" && run_with_timeout 5 story handoff --since "${DURATION}" 2>/dev/null)"
  STORY_STATUS=$?
  if [[ $STORY_STATUS -eq 0 && -n "$STORY_HANDOFF" ]]; then
    printf '\n## Storyhook Handoff\n%s\n' "$STORY_HANDOFF" >> "$HANDOFF_FILE"
  elif [[ $STORY_STATUS -eq 127 ]]; then
    echo "forge: session-stop: no timeout/gtimeout available -- skipped bounded story handoff call" >&2
  fi
fi

# Circuit breaker — prevent stop hook infinite loops. Checked here, AFTER
# the durable checkpoint above (F050), so a trip suppresses only the
# freshen auto-resume signal below -- never the checkpoint that already ran.
_GUARD_LIB="${CLAUDE_PLUGIN_ROOT}/../hook-guard/lib/stop-guard.sh"
# shellcheck source=plugins/hook-guard/lib/stop-guard.sh
[ -f "$_GUARD_LIB" ] && . "$_GUARD_LIB" && stop_guard_check || true

# Best-effort freshen signal for auto-resume.
# Write the signal file directly (bypass freshen.sh to avoid tmux validation
# in hook context — the freshen Stop hook checks tmux availability itself).
FRESHEN_DIR="${PROJECT_DIR}/.freshen"
if [[ -n "${TMUX:-}" ]] && [[ -n "${TMUX_PANE:-}" ]]; then
  mkdir -p "$FRESHEN_DIR"
  # Only write if no cross-source conflict
  CONFLICT=0
  for existing in "$FRESHEN_DIR"/*.signal; do
    [[ -f "$existing" ]] || continue
    existing_source="$(basename "$existing" .signal)"
    if [[ "$existing_source" != "forge" ]]; then
      CONFLICT=1
      break
    fi
  done
  if [[ "$CONFLICT" -eq 0 ]] && [[ ! -f "$FRESHEN_DIR/forge.signal" ]]; then
    printf '/forge resume\nEmergency stop — session interrupted, degraded handoff written\n' > "$FRESHEN_DIR/forge.signal"

    # Send /clear ourselves rather than relying on freshen's own Stop hook
    # (on-stop.sh) to notice this signal in the same Stop-hook batch. Claude
    # Code does not guarantee hook execution order across plugins: if
    # on-stop.sh happens to run before this point, it finds no signal yet
    # (we hadn't written it) and exits without sending /clear, stranding the
    # signal until the next session start deletes it unread. Being
    # self-sufficient here means auto-resume no longer depends on which
    # plugin's Stop hook Claude Code happens to invoke first.
    #
    # Guard against double-sending in the opposite ordering (on-stop.sh runs
    # AFTER this in the same batch and would otherwise also see the signal we
    # just wrote and send its own /clear): .clear-pending is the single
    # "a /clear has already been sent for this Stop event" marker. on-stop.sh
    # checks it too before sending — see plugins/freshen/hooks/on-stop.sh.
    if [[ ! -f "$FRESHEN_DIR/.clear-pending" ]]; then
      touch "$FRESHEN_DIR/.clear-pending"
      tmux send-keys -t "$TMUX_PANE" "/clear" Enter 2>/dev/null || true
    fi
  fi
fi

exit 0
