#!/usr/bin/env bash
# Work Stop hook — auto-save handoff, release lock, set status to paused.
# Only acts if forge is actively running.
#
# Input:  JSON on stdin from Claude Code Stop event
# Output: JSON on stdout (or nothing for no-op)
#
# CRITICAL: Uses jq for all JSON construction.
#
# Every exit path must write to stderr to prevent Claude Code's "No stderr
# output" feedback from creating an infinite conversation loop.

set -uo pipefail
trap '[ $? -eq 0 ] && echo "forge: ok" >&2 || echo "forge: error" >&2' EXIT

# Locate project directory
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-}"

if [[ -z "$PROJECT_DIR" ]]; then
  INPUT="$(cat)" || exit 0
  PROJECT_DIR="$(printf '%s' "$INPUT" | jq -r '.cwd // empty' 2>/dev/null)" || exit 0
else
  cat > /dev/null 2>&1 || true
fi

[[ -z "$PROJECT_DIR" ]] && exit 0

# Check for forge state
STATE_FILE="${PROJECT_DIR}/.forge/state.json"
[[ ! -f "$STATE_FILE" ]] && exit 0

# Verify jq is available
if ! command -v jq &>/dev/null; then
  exit 0
fi

# Read status — only act if running
STATUS="$(jq -r '.status // empty' "$STATE_FILE" 2>/dev/null)" || exit 0
if [[ "$STATUS" != "running" ]]; then
  exit 0
fi

# Derive session duration from lock
LOCK_FILE="${PROJECT_DIR}/.forge/lock.json"
DURATION="unknown"
if [[ -f "$LOCK_FILE" ]]; then
  ACQUIRED_AT="$(jq -r '.acquired_at // empty' "$LOCK_FILE" 2>/dev/null)"
  if [[ -n "$ACQUIRED_AT" ]]; then
    START_EPOCH="$(date -d "$ACQUIRED_AT" +%s 2>/dev/null || echo "")"
    NOW_EPOCH="$(date +%s)"
    if [[ -n "$START_EPOCH" ]]; then
      DURATION_SECS=$(( NOW_EPOCH - START_EPOCH ))
      DURATION="${DURATION_SECS}s"
    fi
  fi
fi

# Write handoff with degraded marker to handoffs directory
mkdir -p "${PROJECT_DIR}/.forge/handoffs"
HANDOFF_FILE="${PROJECT_DIR}/.forge/handoffs/handoff-execute.md"
STORIES_ATTEMPTED="$(jq -r '.stories_attempted // 0' "$STATE_FILE" 2>/dev/null)"
STORIES_THIS="$(jq -r '.stories_this_session // 0' "$STATE_FILE" 2>/dev/null)"

cat > "$HANDOFF_FILE" <<EOF
# Work Handoff

## WARNING: Incomplete Handoff
This handoff was auto-generated by the stop hook. It lacks working context
(patterns, micro-decisions, code landmarks) that a graceful /forge stop would include.
- **source**: stop-hook
- **timestamp**: $(date -u +%Y-%m-%dT%H:%M:%SZ)

## Session Summary
- **Duration**: ${DURATION}
- **Stories completed this session**: ${STORIES_THIS}
- **Stories attempted total**: ${STORIES_ATTEMPTED}
- **Status**: Session ended (stop hook)

## What Happened
Session was terminated (Claude Code stop event). Handoff auto-saved by stop hook.

## What's Next
Run \`/forge resume\` to continue.
EOF

# Generate storyhook handoff if story CLI is available
if command -v story &>/dev/null; then
  STORY_HANDOFF="$(cd "$PROJECT_DIR" && story handoff --since "${DURATION}" 2>/dev/null || true)"
  if [[ -n "$STORY_HANDOFF" ]]; then
    printf '\n## Storyhook Handoff\n%s\n' "$STORY_HANDOFF" >> "$HANDOFF_FILE"
  fi
fi

# Update state in a single jq pipeline: set paused + increment sessions_completed + update timestamp
jq '.status = "paused" | .sessions_completed = (.sessions_completed + 1) | .updated_at = (now | todate)' \
  "$STATE_FILE" > "${STATE_FILE}.tmp" && mv "${STATE_FILE}.tmp" "$STATE_FILE"

# Release lock
rm -f "$LOCK_FILE"

# Best-effort freshen signal for auto-resume.
# Write the signal file directly (bypass freshen.sh to avoid tmux validation
# in hook context — the freshen Stop hook checks tmux availability itself).
FRESHEN_DIR="${PROJECT_DIR}/.freshen"
if [[ -n "${TMUX:-}" ]] && [[ -n "${TMUX_PANE:-}" ]]; then
  mkdir -p "$FRESHEN_DIR"
  # Only write if no cross-source conflict
  CONFLICT=0
  for existing in "$FRESHEN_DIR"/*.signal; do
    [[ -f "$existing" ]] || continue
    existing_source="$(basename "$existing" .signal)"
    if [[ "$existing_source" != "forge" ]]; then
      CONFLICT=1
      break
    fi
  done
  if [[ "$CONFLICT" -eq 0 ]]; then
    echo "/forge resume" > "$FRESHEN_DIR/forge.signal"
  fi
fi

exit 0
