#!/usr/bin/env bash
# End-to-end scenarios for the incremental update flow, scripted against the
# CLI layer exactly as update-protocol.md sequences it (cartographer output is
# simulated by rewriting docs with fixture helpers). These pin the protocol's
# core promises: only affected docs are touched (hash-gating), renames are
# mechanical, orphans are removed cleanly, and conflict-markered docs are
# quarantined and regenerated.

# Three modules + overview, fully covering every source file.
#   src-auth (src/auth/a.txt, src/auth/b.txt)
#   src-api  (src/api/c.txt)  references src-auth  → ripple target
#   src-core (src/core/d.txt)                      → must-stay-byte-identical
_update_fixture() {
    local repo
    repo=$(create_fixture_repo)
    seed_file "$repo" "src/auth/a.txt"
    seed_file "$repo" "src/auth/b.txt"
    seed_file "$repo" "src/api/c.txt"
    seed_file "$repo" "src/core/d.txt"
    write_full_module_doc "$repo" "src-auth" "src/auth" "AuthThing" \
        src/auth/a.txt "" src/auth/b.txt
    write_full_module_doc "$repo" "src-api" "src/api" "ApiThing" \
        src/api/c.txt "src-auth"
    write_full_module_doc "$repo" "src-core" "src/core" "CoreThing" \
        src/core/d.txt
    write_overview_doc "$repo" "ARCHITECTURE" "src" \
        docs/atlas/modules/src-auth.md \
        docs/atlas/modules/src-api.md \
        docs/atlas/modules/src-core.md
    commit_all "$repo"
    run_atlas "$repo" ledger finalize --refresh-hashes
    run_atlas "$repo" index rebuild
    commit_all "$repo" "map"
    echo "$repo"
}

_doc_hash() {
    git -C "$1" hash-object "$2"
}

# INDEX minus its freshness line (the advisory baseline SHA legitimately
# moves with every update; everything else must be byte-stable when no
# summary/read_when/fact changed).
_index_body() {
    grep -v "^Generated by atlas" "$1/docs/atlas/INDEX.md"
}

test_update_flow_edit_touches_only_affected_docs() {
    local repo before_core before_index
    repo=$(_update_fixture)
    before_core=$(_doc_hash "$repo" docs/atlas/modules/src-core.md)
    before_index=$(_index_body "$repo")

    echo "// behavior change" >> "$repo/src/auth/a.txt"
    commit_all "$repo" "edit auth"

    # Plan: src-auth stale (edit), src-api ripple (references src-auth),
    # overview stale (src tree scope), src-core untouched.
    run_atlas "$repo" ledger diff
    assert_json_contains "$OUTPUT" '[.stale_docs[].doc]' "modules/src-auth.md" \
        "edited module planned" || return 1
    assert_json_contains "$OUTPUT" '[.ripple_docs[].doc]' "modules/src-api.md" \
        "dependent doc planned via ripple" || return 1
    assert_json_contains "$OUTPUT" '[.stale_docs[].doc]' "overview/ARCHITECTURE.md" \
        "overview planned via tree scope" || return 1
    assert_json_contains "$OUTPUT" '.unchanged_docs' "modules/src-core.md" \
        "untouched module has zero plan entries" || return 1
    assert_json_field "$OUTPUT" '.dirty_paths | length' "0" \
        "committed edit leaves no dirty paths" || return 1

    # Simulate the cartographer wave on exactly the planned docs.
    write_full_module_doc "$repo" "src-auth" "src/auth" "AuthThing" \
        src/auth/a.txt "" src/auth/b.txt
    write_full_module_doc "$repo" "src-api" "src/api" "ApiThing" \
        src/api/c.txt "src-auth"
    write_overview_doc "$repo" "ARCHITECTURE" "src" \
        docs/atlas/modules/src-auth.md \
        docs/atlas/modules/src-api.md \
        docs/atlas/modules/src-core.md

    run_atlas "$repo" ledger finalize --refresh-hashes
    assert_exit_code 0 "$EXIT_CODE" "finalize ok" || return 1
    run_atlas "$repo" index rebuild
    assert_exit_code 0 "$EXIT_CODE" "index rebuild ok" || return 1
    run_atlas "$repo" lint
    assert_exit_code 0 "$EXIT_CODE" "lint has no errors" || return 1
    run_atlas "$repo" commit --message "docs(atlas): update map"
    assert_json_field "$OUTPUT" '.committed' "true" "update committed" || return 1

    run_atlas "$repo" ledger diff
    assert_json_field "$OUTPUT" '.summary.affected_docs' "0" \
        "map clean after update" || return 1

    # Hash-gating proof: the untouched module doc is byte-identical and the
    # INDEX changed nothing but its freshness line.
    assert_eq "$before_core" "$(_doc_hash "$repo" docs/atlas/modules/src-core.md)" \
        "unchanged doc never rewritten" || return 1
    assert_eq "$before_index" "$(_index_body "$repo")" \
        "INDEX content stable when summaries unchanged" || return 1

    cleanup_fixture_repo "$repo"
}

test_update_flow_rename_needs_no_llm() {
    local repo before_auth before_api
    repo=$(_update_fixture)
    before_auth=$(_doc_hash "$repo" docs/atlas/modules/src-auth.md)
    before_api=$(_doc_hash "$repo" docs/atlas/modules/src-api.md)

    git -C "$repo" mv src/core/d.txt src/core/delta.txt
    git -C "$repo" commit -q -m "rename core file"

    run_atlas "$repo" ledger diff
    assert_json_contains "$OUTPUT" '[.renamed_docs[].doc]' "modules/src-core.md" \
        "pure rename planned as mechanical" || return 1

    run_atlas "$repo" doc apply-renames
    assert_exit_code 0 "$EXIT_CODE" "apply-renames ok" || return 1
    grep -q "src/core/delta.txt:1" "$repo/docs/atlas/modules/src-core.md" \
        || { echo "    FAIL: body location not rewritten"; return 1; }

    run_atlas "$repo" ledger finalize --refresh-hashes
    run_atlas "$repo" index rebuild
    run_atlas "$repo" lint
    assert_exit_code 0 "$EXIT_CODE" "lint clean after rewrite" || return 1
    run_atlas "$repo" commit --message "docs(atlas): apply rename"
    assert_json_field "$OUTPUT" '.committed' "true" "rename committed" || return 1

    run_atlas "$repo" ledger diff
    assert_json_field "$OUTPUT" '.summary.affected_docs' "0" \
        "map clean after mechanical rewrite" || return 1
    assert_eq "$before_auth" "$(_doc_hash "$repo" docs/atlas/modules/src-auth.md)" \
        "unrelated docs untouched by rename" || return 1
    assert_eq "$before_api" "$(_doc_hash "$repo" docs/atlas/modules/src-api.md)" \
        "unrelated docs untouched by rename" || return 1

    cleanup_fixture_repo "$repo"
}

test_update_flow_delete_removes_orphan_and_index_row() {
    local repo
    repo=$(_update_fixture)
    git -C "$repo" rm -q src/core/d.txt
    git -C "$repo" commit -q -m "delete core"

    run_atlas "$repo" ledger diff
    assert_json_contains "$OUTPUT" '[.orphaned_docs[].doc]' "modules/src-core.md" \
        "orphan planned" || return 1

    run_atlas "$repo" doc remove modules/src-core.md
    assert_exit_code 0 "$EXIT_CODE" "orphan removed" || return 1
    # Removing a module doc invalidates the overview's source list — the
    # protocol regenerates the overview whenever module docs change.
    write_overview_doc "$repo" "ARCHITECTURE" "src" \
        docs/atlas/modules/src-auth.md \
        docs/atlas/modules/src-api.md
    run_atlas "$repo" ledger finalize --refresh-hashes
    assert_exit_code 0 "$EXIT_CODE" "finalize ok after overview regen" || return 1
    run_atlas "$repo" index rebuild
    run_atlas "$repo" lint
    assert_exit_code 0 "$EXIT_CODE" "lint clean after orphan removal" || return 1

    if grep -q "src-core" "$repo/docs/atlas/INDEX.md"; then
        echo "    FAIL: INDEX row for the orphan survived the rebuild"
        return 1
    fi
    local in_ledger
    in_ledger=$(jq -r '.docs | has("modules/src-core.md")' \
        "$repo/docs/atlas/atlas-ledger.json")
    assert_eq "false" "$in_ledger" "ledger entry removed" || return 1

    run_atlas "$repo" commit --message "docs(atlas): remove orphaned module"
    assert_json_field "$OUTPUT" '.committed' "true" \
        "doc deletion and INDEX row land in the same commit" || return 1
    run_atlas "$repo" ledger diff
    assert_json_field "$OUTPUT" '.summary.affected_docs' "0" \
        "map clean after orphan removal" || return 1

    cleanup_fixture_repo "$repo"
}

test_update_flow_conflict_marker_quarantine() {
    local repo
    repo=$(_update_fixture)
    {
        echo "<<<<<<< HEAD"
        echo "conflicted line"
        echo "======="
        echo "other line"
        echo ">>>>>>> feature"
    } >> "$repo/docs/atlas/modules/src-core.md"

    run_atlas "$repo" status
    assert_json_field "$OUTPUT" '.tier' "3" "conflict markers force tier 3" || return 1

    # Quarantine: remove the corrupt doc; its sources resurface as new files
    # and the doc is regenerated from code (simulated fresh rewrite).
    run_atlas "$repo" doc remove modules/src-core.md
    assert_exit_code 0 "$EXIT_CODE" "quarantine removal ok" || return 1
    assert_json_contains "$OUTPUT" '.removed[0].sources' "src/core/d.txt" \
        "sources echoed for fresh regeneration" || return 1

    run_atlas "$repo" ledger diff
    assert_json_contains "$OUTPUT" '.new_files' "src/core/d.txt" \
        "quarantined sources resurface as unmapped" || return 1

    write_full_module_doc "$repo" "src-core" "src/core" "CoreThing" \
        src/core/d.txt
    run_atlas "$repo" ledger finalize --refresh-hashes
    run_atlas "$repo" index rebuild
    run_atlas "$repo" lint
    assert_exit_code 0 "$EXIT_CODE" "lint clean after regeneration" || return 1
    run_atlas "$repo" commit --message "docs(atlas): regenerate conflicted doc"

    run_atlas "$repo" status
    assert_json_field "$OUTPUT" '.tier' "0" "map trustworthy again" || return 1

    cleanup_fixture_repo "$repo"
}

test_update_flow_corrupt_frontmatter_quarantine() {
    local repo
    repo=$(_update_fixture)
    # Strip a required key — ledger diff must fail loudly, naming the doc.
    sed -i.bak '/^summary:/d' "$repo/docs/atlas/modules/src-core.md"
    rm -f "$repo/docs/atlas/modules/src-core.md.bak"

    run_atlas "$repo" ledger diff
    assert_exit_code 1 "$EXIT_CODE" "diff refuses invalid frontmatter" || return 1
    assert_json_field "$OUTPUT" '.error' "invalid_frontmatter" "error code" || return 1
    assert_json_field "$OUTPUT" '.docs | has("modules/src-core.md")' "true" \
        "offending doc named" || return 1

    run_atlas "$repo" doc remove modules/src-core.md
    assert_exit_code 0 "$EXIT_CODE" "corrupt doc removable" || return 1
    run_atlas "$repo" ledger diff
    assert_exit_code 0 "$EXIT_CODE" "diff recovers once quarantined" || return 1

    cleanup_fixture_repo "$repo"
}

test_update_flow_clean_map_has_zero_plan_entries() {
    local repo
    repo=$(_update_fixture)

    run_atlas "$repo" ledger diff
    assert_json_field "$OUTPUT" '.summary.affected_docs' "0" "no affected docs" || return 1
    assert_json_field "$OUTPUT" \
        '(.stale_docs + .renamed_docs + .orphaned_docs + .ripple_docs + .fingerprint_stale) | length' \
        "0" "every classification empty" || return 1
    assert_json_field "$OUTPUT" '.new_files | length' "0" "no unmapped files" || return 1
    # Type assertions guard against vacuous passes: jq's `null | length` is 0.
    assert_json_field "$OUTPUT" '.dirty_paths | type' "array" \
        "dirty_paths field present" || return 1
    assert_json_field "$OUTPUT" '.dirty_paths | length' "0" "no dirty paths" || return 1
    assert_json_field "$OUTPUT" '.new_file_assignments.to_existing | type' "array" \
        "assignments field present" || return 1
    assert_json_field "$OUTPUT" \
        '(.new_file_assignments.to_existing + .new_file_assignments.new_modules) | length' \
        "0" "no assignments proposed" || return 1

    cleanup_fixture_repo "$repo"
}
