#!/usr/bin/env bash
# Bare Xcode project layout: <Name>.xcodeproj with NO project.yml anywhere.
#
# This is the default shape of any project not generated by XcodeGen (SCADPad,
# for one). deployit used to refuse it outright — not for any build reason, but
# because it read PRODUCT_BUNDLE_IDENTIFIER and MARKETING_VERSION out of a
# *generator's input file* rather than out of the project. Here they come from
# `xcodebuild -showBuildSettings`, which is the only component whose answer is
# definitionally correct.
#
# xcodebuild is stubbed via tests/fakes/, matching the plugin's gh/tailscale/
# launchctl fakes, so the suite stays hermetic.

set -uo pipefail
TESTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(cd "$TESTS_DIR/.." && pwd)"
export PYTHONDONTWRITEBYTECODE=1

PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); printf '  PASS  %s\n' "$1"; }
bad()  { FAIL=$((FAIL+1)); printf '  FAIL  %s\n' "$1"; [[ -n "${2:-}" ]] && printf '%s\n' "$2" | sed 's/^/        /'; }

# A throwaway git repo containing only the layout signals under test.
make_repo() {
    local repo; repo=$(mktemp -d)
    git -C "$repo" init -q
    git -C "$repo" config user.email test@test
    git -C "$repo" config user.name  test
    git -C "$repo" commit -q --allow-empty -m init
    mkdir -p "$repo/SCADPad.xcodeproj"
    touch "$repo/SCADPad.xcodeproj/project.pbxproj"
    printf '%s' "$repo"
}

# Run `deploy --__dump-metadata` in $repo with the fake xcodebuild first on PATH.
dump() {
    local repo="$1"; shift
    ( cd "$repo" && PATH="$TESTS_DIR/fakes:$PATH" \
        python3 "$PLUGIN_ROOT/bin/deployit-cli" --plugin-root "$PLUGIN_ROOT" \
        deploy --platform ios --__dump-metadata "$@" 2>&1 )
}

# ---------------------------------------------------------------- 1. bare proj
repo=$(make_repo)
out=$(FAKE_XCODEBUILD_BUNDLE_ID=io.mikey.SCADPad FAKE_XCODEBUILD_VERSION=1.4.2 dump "$repo")
t="bare .xcodeproj resolves metadata from xcodebuild"
if   ! grep -q '"project": "SCADPad"'                  <<<"$out"; then bad "$t (project)"        "$out"
elif ! grep -q '"bundle_id": "io.mikey.SCADPad"'       <<<"$out"; then bad "$t (bundle_id)"      "$out"
elif ! grep -q '"marketing_version": "1.4.2"'          <<<"$out"; then bad "$t (version)"        "$out"
elif ! grep -q '"xcode_container_flag": "-project"'    <<<"$out"; then bad "$t (container flag)" "$out"
elif ! grep -q '"default_scheme": "SCADPad"'           <<<"$out"; then bad "$t (scheme)"         "$out"
elif ! grep -q '"project_yml": null'                   <<<"$out"; then bad "$t (project_yml)"    "$out"
else ok "$t"; fi
rm -rf "$repo"

# ------------------------------------------------- 2. workspace wins as container
repo=$(make_repo); mkdir -p "$repo/SCADPad.xcworkspace"
out=$(dump "$repo")
t="a sibling .xcworkspace is preferred as the archive container"
if   ! grep -q '"xcode_container_flag": "-workspace"'      <<<"$out"; then bad "$t (flag)" "$out"
elif ! grep -q '"xcode_container_path": ".*\.xcworkspace"' <<<"$out"; then bad "$t (path)" "$out"
else ok "$t"; fi
rm -rf "$repo"

# ---------------------------------------------------- 3. --scheme reaches argv
repo=$(make_repo); log=$(mktemp)
out=$(FAKE_XCODEBUILD_ARGV_LOG="$log" dump "$repo" --scheme SCADPad-Alt)
t="--scheme overrides the scheme the settings query asks about"
if grep -q -- "-scheme SCADPad-Alt" "$log"; then ok "$t"; else bad "$t" "$out"; cat "$log"; fi
rm -rf "$repo" "$log"

# ------------------------------------------- 4. xcodebuild silent -> loud refusal
repo=$(make_repo)
out=$(FAKE_XCODEBUILD_FAIL=1 dump "$repo")
t="an unanswerable xcodebuild refuses loudly instead of defaulting"
if   grep -q '"ok": true'  <<<"$out"; then bad "$t (deploy proceeded)" "$out"
elif ! grep -q 'SCADPad'   <<<"$out"; then bad "$t (refusal does not name the scheme)" "$out"
else ok "$t"; fi
rm -rf "$repo"

# --------------------------------- 5. a missing setting is named, not defaulted
repo=$(make_repo)
out=$(FAKE_XCODEBUILD_BUNDLE_ID="" dump "$repo")
t="a settings answer missing PRODUCT_BUNDLE_IDENTIFIER is refused by name"
if   grep -q '"ok": true'                    <<<"$out"; then bad "$t (deploy proceeded)" "$out"
elif ! grep -q 'PRODUCT_BUNDLE_IDENTIFIER'   <<<"$out"; then bad "$t (key not named)"    "$out"
else ok "$t"; fi
rm -rf "$repo"

# ------------------------------------------ 6. existing layout still takes over
repo=$(make_repo)
cat > "$repo/project.yml" <<'YAML'
name: SCADPad
targets:
  SCADPad:
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.example.fromyaml
        MARKETING_VERSION: "0.0.1"
YAML
out=$(FAKE_XCODEBUILD_BUNDLE_ID=io.mikey.SCADPad dump "$repo")
t="a present project.yml still wins over the bare-project arm"
if   ! grep -q '"bundle_id": "io.example.fromyaml"'  <<<"$out"; then bad "$t (bundle_id)"   "$out"
elif ! grep -q '"project_yml": ".*/project.yml"'     <<<"$out"; then bad "$t (project_yml)" "$out"
else ok "$t"; fi
rm -rf "$repo"

printf '\nResults: %d passed, %d failed\n' "$PASS" "$FAIL"
[[ $FAIL -eq 0 ]]
